version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: db-diemdanh
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: diemdanh
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-diemdanh
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/nghiemmmm/online-attendance-system/attendance-backend:latest
    container_name: backend-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/nghiemmmm/online-attendance-system/attendance-frontend:latest
    container_name: frontend-app
    depends_on:
      - backend

  face-recognition:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/nghiemmmm/online-attendance-system/attendance-backend:latest
    container_name: face-recognition-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ec2.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
      - face-recognition
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 15s
      timeout: 10s
      retries: 3

volumes:
  pgvector_data:
  redis_data: