"""initial schema

Revision ID: 284f4b8e6723
Revises: 
Create Date: 2026-05-27 22:12:46.832612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '284f4b8e6723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hocphan',
    sa.Column('ten_hoc_phan', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('mo_ta', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('so_tin_chi', sa.Integer(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('ma_hoc_phan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ma_hoc_phan')
    )
    op.create_table('nganh',
    sa.Column('ten_nganh', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mo_ta', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ma_nganh', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ma_nganh')
    )
    op.create_table('taikhoan',
    sa.Column('vai_tro', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('ma_tai_khoan', sa.Integer(), nullable=False),
    sa.Column('ten_dang_nhap', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('mat_khau_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('lan_dang_nhap_cuoi', sa.DateTime(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ma_tai_khoan')
    )
    op.create_index(op.f('ix_taikhoan_ten_dang_nhap'), 'taikhoan', ['ten_dang_nhap'], unique=True)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('canbo',
    sa.Column('ho', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ten', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('dien_thoai', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('gioi_tinh', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ma_tai_khoan', sa.Integer(), nullable=True),
    sa.Column('chuc_vu', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('ma_can_bo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_tai_khoan'], ['taikhoan.ma_tai_khoan'], ),
    sa.PrimaryKeyConstraint('ma_can_bo'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ma_tai_khoan')
    )
    op.create_table('sinhvien',
    sa.Column('ho', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ten', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('gioi_tinh', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('dien_thoai', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ma_nganh', sa.Integer(), nullable=False),
    sa.Column('ma_tai_khoan', sa.Integer(), nullable=True),
    sa.Column('trang_thai_hoc', sa.Boolean(), nullable=False),
    sa.Column('ma_sinh_vien', sa.Integer(), nullable=False),
    sa.Column('thoi_gian_bat_dau_hoc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ma_nganh'], ['nganh.ma_nganh'], ),
    sa.ForeignKeyConstraint(['ma_tai_khoan'], ['taikhoan.ma_tai_khoan'], ),
    sa.PrimaryKeyConstraint('ma_sinh_vien'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ma_tai_khoan')
    )
    op.create_table('anhkhuonmat',
    sa.Column('duong_dan_anh', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('loai_anh', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('ma_anh', sa.Integer(), nullable=False),
    sa.Column('ma_sinh_vien', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['ma_sinh_vien'], ['sinhvien.ma_sinh_vien'], ),
    sa.PrimaryKeyConstraint('ma_anh')
    )
    op.create_table('lophocphan',
    sa.Column('ma_hoc_phan', sa.Integer(), nullable=False),
    sa.Column('ma_can_bo', sa.Integer(), nullable=False),
    sa.Column('hoc_ky', sa.Integer(), nullable=True),
    sa.Column('nam_hoc', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('ty_le_chuyen_can_toi_thieu', sa.Float(), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('ma_lop_hoc_phan', sa.Integer(), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ma_can_bo'], ['canbo.ma_can_bo'], ),
    sa.ForeignKeyConstraint(['ma_hoc_phan'], ['hocphan.ma_hoc_phan'], ),
    sa.PrimaryKeyConstraint('ma_lop_hoc_phan')
    )
    op.create_table('buoihoc',
    sa.Column('ngay_hoc', sa.Date(), nullable=False),
    sa.Column('gio_bat_dau', sa.Time(), nullable=True),
    sa.Column('gio_ket_thuc', sa.Time(), nullable=True),
    sa.Column('so_buoi', sa.Integer(), nullable=True),
    sa.Column('trang_thai', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('nguong_nhan_dien', sa.Float(), nullable=False),
    sa.Column('so_phut_muon_toi_da', sa.Integer(), nullable=False),
    sa.Column('ghi_chu', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ma_buoi_hoc', sa.Integer(), nullable=False),
    sa.Column('ma_lop_hoc_phan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_lop_hoc_phan'], ['lophocphan.ma_lop_hoc_phan'], ),
    sa.PrimaryKeyConstraint('ma_buoi_hoc')
    )
    op.create_table('dangkyhocphan',
    sa.Column('ma_sinh_vien', sa.Integer(), nullable=False),
    sa.Column('ma_lop_hoc_phan', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('ngay_dang_ky', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ma_lop_hoc_phan'], ['lophocphan.ma_lop_hoc_phan'], ),
    sa.ForeignKeyConstraint(['ma_sinh_vien'], ['sinhvien.ma_sinh_vien'], ),
    sa.PrimaryKeyConstraint('ma_sinh_vien', 'ma_lop_hoc_phan')
    )
    op.create_table('thoikhoabieu',
    sa.Column('thu', sa.Integer(), nullable=False),
    sa.Column('tiet_bat_dau', sa.Integer(), nullable=True),
    sa.Column('tiet_ket_thuc', sa.Integer(), nullable=True),
    sa.Column('gio_bat_dau', sa.Time(), nullable=True),
    sa.Column('gio_ket_thuc', sa.Time(), nullable=True),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=False),
    sa.Column('ma_thoi_khoa_bieu', sa.Integer(), nullable=False),
    sa.Column('ma_lop_hoc_phan', sa.Integer(), nullable=False),
    sa.CheckConstraint('ngay_bat_dau < ngay_ket_thuc', name='ck_tkb_ngay'),
    sa.ForeignKeyConstraint(['ma_lop_hoc_phan'], ['lophocphan.ma_lop_hoc_phan'], ),
    sa.PrimaryKeyConstraint('ma_thoi_khoa_bieu')
    )
    op.create_table('diemdanh',
    sa.Column('ma_sinh_vien', sa.Integer(), nullable=False),
    sa.Column('ma_buoi_hoc', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('phuong_thuc', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('do_tin_cay', sa.Float(), nullable=True),
    sa.Column('thoi_diem_diem_danh', sa.DateTime(), nullable=True),
    sa.Column('ly_do_chinh_sua', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ma_diem_danh', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_buoi_hoc'], ['buoihoc.ma_buoi_hoc'], ),
    sa.ForeignKeyConstraint(['ma_sinh_vien'], ['sinhvien.ma_sinh_vien'], ),
    sa.PrimaryKeyConstraint('ma_diem_danh'),
    sa.UniqueConstraint('ma_sinh_vien', 'ma_buoi_hoc', name='uq_diemdanh_sv_buoi')
    )
    op.create_table('anhdiemdanh',
    sa.Column('duong_dan_anh', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ma_anh', sa.Integer(), nullable=False),
    sa.Column('ma_diem_danh', sa.Integer(), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ma_diem_danh'], ['diemdanh.ma_diem_danh'], ),
    sa.PrimaryKeyConstraint('ma_anh')
    )
    op.create_table('khieunai',
    sa.Column('ma_diem_danh', sa.Integer(), nullable=False),
    sa.Column('ma_sinh_vien', sa.Integer(), nullable=False),
    sa.Column('ly_do', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('trang_thai', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('ma_can_bo_xu_ly', sa.Integer(), nullable=True),
    sa.Column('ghi_chu_xu_ly', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ngay_xu_ly', sa.DateTime(), nullable=True),
    sa.Column('ma_khieu_nai', sa.Integer(), nullable=False),
    sa.Column('ngay_gui', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ma_can_bo_xu_ly'], ['canbo.ma_can_bo'], ),
    sa.ForeignKeyConstraint(['ma_diem_danh'], ['diemdanh.ma_diem_danh'], ),
    sa.ForeignKeyConstraint(['ma_sinh_vien'], ['sinhvien.ma_sinh_vien'], ),
    sa.PrimaryKeyConstraint('ma_khieu_nai')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('khieunai')
    op.drop_table('anhdiemdanh')
    op.drop_table('diemdanh')
    op.drop_table('thoikhoabieu')
    op.drop_table('dangkyhocphan')
    op.drop_table('buoihoc')
    op.drop_table('lophocphan')
    op.drop_table('anhkhuonmat')
    op.drop_table('sinhvien')
    op.drop_table('canbo')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_taikhoan_ten_dang_nhap'), table_name='taikhoan')
    op.drop_table('taikhoan')
    op.drop_table('nganh')
    op.drop_table('hocphan')
    # ### end Alembic commands ###
