"""initial schema

Revision ID: 284f4b8e6723
Revises:
Create Date: 2026-05-27 22:12:46.832612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '284f4b8e6723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('credit_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('major',
    sa.Column('major_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('major_id')
    )
    op.create_table('accounts',
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('staff',
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('students',
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('academic_status', sa.Boolean(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('study_started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.major_id'], ),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('face_images',
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('image_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('class_sections',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('minimum_attendance_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('class_section_id')
    )
    op.create_table('class_sessions',
    sa.Column('class_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('recognition_threshold', sa.Float(), nullable=False),
    sa.Column('late_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], ),
    sa.PrimaryKeyConstraint('class_session_id')
    )
    op.create_table('course_registrations',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_section_id')
    )
    op.create_table('timetables',
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=True),
    sa.Column('end_period', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('start_date < end_date', name='ck_timetable_dates'),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.class_section_id'], ),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    op.create_table('attendance',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attendance_time', sa.DateTime(), nullable=True),
    sa.Column('edit_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.class_session_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('student_id', 'class_session_id', name='uq_attendance_student_session')
    )
    op.create_table('attendance_images',
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.attendance_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('appeals',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('resolver_staff_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('appeal_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolver_staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.attendance_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('appeal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeals')
    op.drop_table('attendance_images')
    op.drop_table('attendance')
    op.drop_table('timetables')
    op.drop_table('course_registrations')
    op.drop_table('class_sessions')
    op.drop_table('class_sections')
    op.drop_table('face_images')
    op.drop_table('students')
    op.drop_table('staff')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('major')
    op.drop_table('courses')
    # ### end Alembic commands ###
