"""add_lockout_fields

Revision ID: af1a6e05955d
Revises: d4e5f6a7b8c9
Create Date: 2026-06-24 15:23:38.615697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = 'af1a6e05955d'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely drop tables and columns if they exist to prevent crashes on clean database boots
    op.execute("""
    DO $$
    BEGIN
        -- Drop tables if they exist
        IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'system_logs') THEN
            DROP TABLE system_logs CASCADE;
        END IF;
        IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'cauhinhhethong') THEN
            DROP TABLE cauhinhhethong CASCADE;
        END IF;
        IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'attendance_history') THEN
            DROP TABLE attendance_history CASCADE;
        END IF;

        -- Drop columns if the tables and columns exist
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'class_sessions' AND column_name = 'attendance_opened_at') THEN
            ALTER TABLE class_sessions DROP COLUMN attendance_opened_at;
        END IF;
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'class_sessions' AND column_name = 'attendance_closed_at') THEN
            ALTER TABLE class_sessions DROP COLUMN attendance_closed_at;
        END IF;
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'appeals' AND column_name = 'evidence_path') THEN
            ALTER TABLE appeals DROP COLUMN evidence_path;
        END IF;
    END $$;
    """)
    op.add_column('accounts', sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('accounts', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'locked_until')
    op.drop_column('accounts', 'failed_login_count')
    op.add_column('appeals', sa.Column('evidence_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('attendance_closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('attendance_opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('attendance_history',
    sa.Column('history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attendance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('new_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name=op.f('lichsudiemdanh_ma_can_bo_fkey')),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.attendance_id'], name=op.f('lichsudiemdanh_ma_diem_danh_fkey')),
    sa.PrimaryKeyConstraint('history_id', name=op.f('lichsudiemdanh_pkey'))
    )
    op.create_table('cauhinhhethong',
    sa.Column('gia_tri', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('khoa', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('khoa', name=op.f('cauhinhhethong_pkey'))
    )
    op.create_table('system_logs',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('old_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('nhatkyhethong_ma_tai_khoan_fkey')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('nhatkyhethong_pkey'))
    )
    # ### end Alembic commands ###
