"""add_lockout_fields

Revision ID: af1a6e05955d
Revises: d4e5f6a7b8c9
Create Date: 2026-06-24 15:23:38.615697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = 'af1a6e05955d'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nhatkyhethong')
    op.drop_table('cauhinhhethong')
    op.drop_table('lichsudiemdanh')
    op.drop_column('buoihoc', 'thoi_gian_mo_diem_danh')
    op.drop_column('buoihoc', 'thoi_gian_dong_diem_danh')
    op.drop_column('khieunai', 'duong_dan_minh_chung')
    op.add_column('taikhoan', sa.Column('so_lan_dang_nhap_sai', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('taikhoan', sa.Column('thoi_gian_khoa', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taikhoan', 'thoi_gian_khoa')
    op.drop_column('taikhoan', 'so_lan_dang_nhap_sai')
    op.add_column('khieunai', sa.Column('duong_dan_minh_chung', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('buoihoc', sa.Column('thoi_gian_dong_diem_danh', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('buoihoc', sa.Column('thoi_gian_mo_diem_danh', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('lichsudiemdanh',
    sa.Column('ma_lich_su', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ma_diem_danh', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ma_can_bo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trang_thai_cu', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('trang_thai_moi', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('ly_do', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('thoi_gian', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ma_can_bo'], ['canbo.ma_can_bo'], name=op.f('lichsudiemdanh_ma_can_bo_fkey')),
    sa.ForeignKeyConstraint(['ma_diem_danh'], ['diemdanh.ma_diem_danh'], name=op.f('lichsudiemdanh_ma_diem_danh_fkey')),
    sa.PrimaryKeyConstraint('ma_lich_su', name=op.f('lichsudiemdanh_pkey'))
    )
    op.create_table('cauhinhhethong',
    sa.Column('gia_tri', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mo_ta', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('khoa', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ngay_cap_nhat', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('khoa', name=op.f('cauhinhhethong_pkey'))
    )
    op.create_table('nhatkyhethong',
    sa.Column('ma_nhat_ky', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ma_tai_khoan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hanh_dong', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('doi_tuong', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('doi_tuong_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('du_lieu_cu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('du_lieu_moi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thoi_gian', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ma_tai_khoan'], ['taikhoan.ma_tai_khoan'], name=op.f('nhatkyhethong_ma_tai_khoan_fkey')),
    sa.PrimaryKeyConstraint('ma_nhat_ky', name=op.f('nhatkyhethong_pkey'))
    )
    # ### end Alembic commands ###
